# Generated by Django 4.2.1 on 2023-08-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightplan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drones',
            name='user',
            field=models.ManyToManyField(to='flightplan.flights'),
        ),
    ]
